apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-text-summary
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ds-text-summary
  template:
    metadata:
      labels:
        app: ds-text-summary
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
        - name: ds-text-summary
          image: alexdragnea/ds-text-summary:latest
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 9G
              ephemeral-storage: 6G
            requests:
              memory: 7G
              ephemeral-storage: 4G
          ports:
            - containerPort: 9999
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9999
            initialDelaySeconds: 200
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9999
            initialDelaySeconds: 200
            periodSeconds: 5
