apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ds-text-summary-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ds-text-summary
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70