name: Build & Deploy

on:
  workflow_dispatch:

env:
  PROJECT_ID: ds-cluster-408911
  GKE_CLUSTER: ds-cluster-gpu  
  GKE_ZONE: me-west1
  SERVICE_ACCOUNT_KEY: ${{ secrets.GK_SA_KEY }}

jobs:
  build-and-push-to-dockerhub:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip'
    
    - name: Print Python Version
      run: |
        python3 --version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Docker Build and Push to DockerHub
      run: |
        docker build -t alexdragnea/ds-text-summary:latest .
        docker push alexdragnea/ds-text-summary:latest
  
  deploy-to-gke:
    needs: build-and-push-to-dockerhub
    name: Deploy to GKE
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GK_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GK_SA_KEY }}

    - name: Deploy
      run: |
        kubectl apply -f https://raw.githubusercontent.com/alexdragnea/DS_TextSummary/main/manifests/service.yaml 
        sleep 10 
        kubectl apply -f https://raw.githubusercontent.com/alexdragnea/DS_TextSummary/main/manifests/deployment.yaml 
        sleep 180 
        kubectl apply -f https://raw.githubusercontent.com/alexdragnea/DS_TextSummary/main/manifests/hpa.yaml 
        kubectl get pods
        sleep 60
        kubectl get svc
        kubectl get hpa
